### ISSUE TITLE
Could you please add some instructions on how to use the library ? 

### ISSUE THREAD

**Issue by prasang-readwhere** [mparticle-integrations/mparticle-javascript-integration-onetrust#30]
I am confused due to lack of instructions in the library. Do I just need to install the library and we are good to go ? Is onetrust automatically integrated ? 
Please help

**Comment by rmi22186** [comment]
Hi @prasang-readwhere  - 

Apologies for not seeing this sooner.  Are you currently a customer of mParticle?  The documentation can be found here - https://docs.mparticle.com/integrations/onetrust/event/.

**Comment by rmi22186** [comment]
If that doesn't help, please reopen this issue. Thanks!
